logging:
  config: classpath:logback.xml


server:
  port: 8088
spring:
  application:
    name: account-auth-service
  profiles:
    active: dev

#暴露所有
management:
  endpoints:
    web:
      exposure:
        include: "*"
